global:

route:
  receiver: 'Default'
  group_wait: 15s
  group_interval: 15s
  repeat_interval: 1m
  group_by: ['alertname']

#  routes:
#  - receiver: AlertasPrometheus
#    match:
#      test: alertmanager

receivers:
- name: Default
  webhook_configs:
  - url: 'https://pruu.herokuapp.com/dump/brunobizarridefault'
- name: AlertPrometheus
  webhook_configs:
  - url: 'https://pruu.herokuapp.com/dump/brunobizarri-prometheus'
- name: AlertNode
  webhook_configs:
  - url: 'https://pruu.herokuapp.com/dump/brunobizarri-node'