version: '3.9'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    networks:
      - prometheus
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert.prometheus.rules.yaml:/etc/prometheus/alert.prometheus.rules
      - ./prometheus/alert.node.rules.yaml:/etc/prometheus/alert.node.rules
      - ./prometheus/alert.queue.rules.yaml:/etc/prometheus/alert.queue.rules

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    networks:
      - prometheus
    depends_on:
      - prometheus
    volumes:
      - ./alertmanager/alertmanager.yaml:/etc/alertmanager/alertmanager.yml

  bull-exporter:
    image: uphabit/bull_exporter
    env_file:
      - bull_exporter/.env
    ports:
      - 9538:9538
    networks:
      - prometheus
    depends_on:
      - prometheus

  # nodejs-bull-monitor:
  #   image: ejhayes/nodejs-bull-monitor
  #   env_file:
  #     - nodejs-bull-monitor/.env
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - prometheus
  #   depends_on:
  #     - prometheus

  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100
    networks:
      - prometheus
    depends_on:
      - prometheus

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025

networks:
  prometheus:
    driver: bridge