version: '3.9'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    networks:
      - prometheus
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    networks:
      - prometheus
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100
    networks:
      - prometheus
    depends_on:
      - prometheus

networks:
  prometheus:
    driver: bridge
