version: '3.9'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    networks:
      - prometheus
    volumes:
      - ./prometheus:/etc/prometheus/

  # mac_exporter:
  #   image: quay.io/prometheus/node-exporter:latest
  #   container_name: mac_exporter
  #   command:
  #     - '--path.rootfs=/host'
  #   network_mode: host
  #   pid: host
  #   volumes:
  #     - '/:/host:ro'

networks:
  prometheus:
    driver: bridge