version: '3.9'

services:
  prometheus:
    image: prom/prometheus
    network_mode: host
    # ports:
    #   - 9090:9090
    # networks:
    #   - prometheus
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml

  # mac_exporter:
  #   image: quay.io/prometheus/node-exporter:latest
  #   container_name: mac_exporter
  #   command:
  #     - '--path.rootfs=/host'
  #   network_mode: host
  #   pid: host
  #   volumes:
  #     - '/:/host:ro'

networks:
  prometheus:
    driver: bridge
