version: '3.9'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    networks:
      - prometheus

  mongodb:
    image: mongo:4.2.1
    networks:
      - prometheus
    restart: always
    environment:
      MONGO_INIT_ROOT_USERNAME: mongouser
      MONGO_INIT_ROOT_PASSWORD: 987654321

  # mongo_exporter:
  #   image: frabricioveronez/mongo_exporter
  #   networks:
  #     - prometheus
  #   depends_on:
  #     - mongodb

networks:
  prometheus:
    driver: bridge