groups:
- name: QueueAlerts
  rules:

  - alert: JobWait
    expr: bull_queue_waiting{job=~"bull-.*",queue=~".*"} != 0
    for: 0m
    labels:
      scrape: bull-exporter
      severity: warning
    annotations:
      summary: Fila com Job aguardando
      description: "Fila {{$labels.queue}} no ambiente {{$labels.job}} tem um job aguardando a mais de 1 minuto"

  - alert: JobWaitMore5Minute
    expr: bull_queue_waiting{job=~"bull-.*",queue=~".*"} != 0
    for: 5m
    labels:
      scrape: bull-exporter
      severity: hight
    annotations:
      summary: Fila com Job aguardando
      description: "Fila {{$labels.queue}} no ambiente {{$labels.job}} tem um job aguardando a mais de 5 minuto"

  - alert: JobFailedDEV
    expr: bull_queue_failed{job=~"bull-.*",queue=~"DEV_.*"} > 1
    for: 0m
    labels:
      scrape: bull-exporter
      severity: warning
    annotations:
      summary: Fila {{$labels.queue}} - Jobs com falha
      description: "Fila {{$labels.queue}} no ambiente {{$labels.job}} tem um jobs falhando"

  - alert: JobFailedDEV2
    expr: bull_queue_failed{job=~"bull-.*",queue=~"DEV2_.*"} > 1
    for: 0m
    labels:
      scrape: bull-exporter
      severity: higth
    annotations:
      summary: Fila {{$labels.queue}} - Jobs com falha
      description: "Fila {{$labels.queue}} no ambiente {{$labels.job}} tem um jobs falhando"

  - alert: JobFailedRate5Minutes
    expr: rate(bull_queue_failed{job=~"bull-.*",queue=~".*"}[5m]) > 2
    for: 1m
    labels:
      scrape: bull-exporter
      severity: hight
    annotations:
      summary: Fila {{$labels.queue}} - Jobs com falha
      description: "Fila {{$labels.queue}} no ambiente {{$labels.job}} tem um jobs falhando"