global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
  - alert.prometheus.rules
  - alert.node.rules
  - alert.queue.rules

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090

- job_name: node-exporter
  static_configs:
    - targets:
      - node-exporter:9100

- job_name: bull-exporter
  static_configs:
    - targets:
      - bull-exporter:9538